apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-gitops06
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops06

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops06
      - op: replace
        path: /spec/clusterName
        value: gitops06

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops06
      - op: replace
        path: /spec/controllerRef/name
        value: gitops06
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops06
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops06
      - op: replace
        path: /spec/controllerRef/name
        value: gitops06
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops06

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops06
      - op: replace
        path: /data/slurm.key
        value: 9NFqbi/tbOOH1aq1VcPFmSDZYRETcZq7OXAldhQur7pXgOxkSffzETedY1xfCwb45ml6BC3G5jqFYaorXe7K6w==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops06
      - op: replace
        path: /data/jwt.key
        value: r1zTnwViEVGuYMG9vU89pdo/3kAiElAnectAKUn2zGU=
