apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-e2e-v1
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: e2e-v1

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-v1
      - op: replace
        path: /metadata/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /spec/clusterName
        value: e2e-v1

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-v1-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /spec/controllerRef/name
        value: e2e-v1
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-v1
      - op: replace
        path: /metadata/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /spec/controllerRef/name
        value: e2e-v1
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-e2e-v1

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /data/slurm.key
        value: +wSRHKzQMACfnxx7YKQ1MUVtV2KoJ+Z+FySECR64jljP3HCxtA9yOGS1wgxBjjPxxeiaeSQEpw6kWLZXUKW38Q==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-e2e-v1
      - op: replace
        path: /data/jwt.key
        value: hBrH4iJH8/p6M1j/aWiav+Mbod4U5jwdrpNr7QXFLEo=
