apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/tenant-infra

# Per-tenant patches
patches:
  # Namespace
  - target:
      kind: Namespace
      name: NAMESPACE
    patch: |
      - op: replace
        path: /metadata/name
        value: example
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: example

  # TenantControlPlane
  - target:
      kind: TenantControlPlane
      name: CLUSTER_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: example
      - op: replace
        path: /metadata/namespace
        value: example
      - op: replace
        path: /spec/kubernetes/version
        value: "v1.30.0"
      - op: replace
        path: /spec/controlPlane/ingress/hostname
        value: example.k8s.launcher.internal
      - op: replace
        path: /spec/networkProfile/certSANs/0
        value: example.k8s.launcher.internal

  # CAPI Cluster
  - target:
      kind: Cluster
      name: CLUSTER_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: example
      - op: replace
        path: /metadata/namespace
        value: example
      - op: replace
        path: /spec/controlPlaneEndpoint/host
        value: example.k8s.launcher.internal
      - op: replace
        path: /spec/infrastructureRef/name
        value: example

  # OpenStackCluster
  - target:
      kind: OpenStackCluster
      name: CLUSTER_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: example
      - op: replace
        path: /metadata/namespace
        value: example

  # OpenStackMachineTemplate
  - target:
      kind: OpenStackMachineTemplate
      name: CLUSTER_NAME-worker-mt
    patch: |
      - op: replace
        path: /metadata/name
        value: example-worker-mt
      - op: replace
        path: /metadata/namespace
        value: example
      - op: replace
        path: /spec/template/spec/flavor
        value: m1.xlarge

  # KubeadmConfigTemplate
  - target:
      kind: KubeadmConfigTemplate
      name: CLUSTER_NAME-worker-config
    patch: |
      - op: replace
        path: /metadata/name
        value: example-worker-config
      - op: replace
        path: /metadata/namespace
        value: example

  # MachineDeployment
  - target:
      kind: MachineDeployment
      name: CLUSTER_NAME-md-0
    patch: |
      - op: replace
        path: /metadata/name
        value: example-md-0
      - op: replace
        path: /metadata/namespace
        value: example
      - op: replace
        path: /spec/clusterName
        value: example
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/clusterName
        value: example
      - op: replace
        path: /spec/template/spec/version
        value: v1.30.0
      - op: replace
        path: /spec/template/spec/bootstrap/configRef/name
        value: example-worker-config
      - op: replace
        path: /spec/template/spec/infrastructureRef/name
        value: example-worker-mt

  # ClusterResourceSet
  - target:
      kind: ClusterResourceSet
      name: cilium-cni
    patch: |
      - op: replace
        path: /metadata/namespace
        value: example
