
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: emerald-storm-cluster-big-mt
  namespace: slurm-emerald-storm-cluster
spec:
  template:
    spec:
      flavor: a4v2
      image:
        filter:
          name: ubuntu-2404-kube-v1.30.0
      sshKeyName: capi-test
      identityRef:
        name: cloud-config
        cloudName: capi-test
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: emerald-storm-cluster-big
  namespace: slurm-emerald-storm-cluster
spec:
  clusterName: emerald-storm-cluster
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: emerald-storm-cluster
      cluster.x-k8s.io/deployment-name: emerald-storm-cluster-big
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: emerald-storm-cluster
        cluster.x-k8s.io/deployment-name: emerald-storm-cluster-big
    spec:
      clusterName: emerald-storm-cluster
      version: v1.30.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: emerald-storm-cluster-worker-config
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: emerald-storm-cluster-big-mt
