apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-token-test
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: e2e-token-test

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-token-test
      - op: replace
        path: /metadata/namespace
        value: e2e-token-test
      - op: replace
        path: /spec/clusterName
        value: e2e-token-test

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-token-test-workers
      - op: replace
        path: /metadata/namespace
        value: e2e-token-test
      - op: replace
        path: /spec/controllerRef/name
        value: e2e-token-test
      - op: replace
        path: /spec/controllerRef/namespace
        value: e2e-token-test
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e-token-test
      - op: replace
        path: /metadata/namespace
        value: e2e-token-test
      - op: replace
        path: /spec/controllerRef/name
        value: e2e-token-test
      - op: replace
        path: /spec/controllerRef/namespace
        value: e2e-token-test

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: e2e-token-test
      - op: replace
        path: /data/slurm.key
        value: PSEUUIDNYXvnbGgs3O8lPJUqInoZGzO6OFIZ8aWdX/3L6sorF4Ei3uMHssbdem53O9UcestLAo5Z/c5lYIJ9sw==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: e2e-token-test
      - op: replace
        path: /data/jwt.key
        value: Uj5WNH47/GvTBGHjVY9XfT5mc/st4km1ll6hD/6ful4=
