apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-gitops04
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops04

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops04
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops04
      - op: replace
        path: /spec/clusterName
        value: gitops04

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops04-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops04
      - op: replace
        path: /spec/controllerRef/name
        value: gitops04
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops04
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops04
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops04
      - op: replace
        path: /spec/controllerRef/name
        value: gitops04
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops04

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops04
      - op: replace
        path: /data/slurm.key
        value: vaBJmTuZOJzXNYz50VIWi0s7PlgFKjx3FMTtdb+SAlWYTnjmgprpQ04AmC+918zO5RX87MPLlWhMem8cUq4RMg==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops04
      - op: replace
        path: /data/jwt.key
        value: PBkSwCEW6d8xRcDtPT17GK+vBxDBRvSe0cM72ma/iQw=
