apiVersion: v1
kind: Secret
metadata:
  name: test-slurm-ux-sssd-conf
  namespace: slurm-test-slurm-ux
type: Opaque
data:
  sssd.conf: W3Nzc2RdCmNvbmZpZ19maWxlX3ZlcnNpb24gPSAyCnNlcnZpY2VzID0gbnNzLCBwYW0KZG9tYWlucyA9IEZJTEVTCgpbbnNzXQpmaWx0ZXJfdXNlcnMgPSByb290CmZpbHRlcl9ncm91cHMgPSByb290CgpbcGFtXQoKW2RvbWFpbi9GSUxFU10KaWRfcHJvdmlkZXIgPSBmaWxlcwplbnVtZXJhdGUgPSB0cnVlCg==
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: test-slurm-ux-login
  namespace: slurm-test-slurm-ux
spec:
  controllerRef:
    name: test-slurm-ux
    namespace: slurm-test-slurm-ux
  replicas: 1
  sssdConfRef:
    name: test-slurm-ux-sssd-conf
    key: sssd.conf
  rootSshAuthorizedKeys: |-
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtestkeyforuxtest2026ABCDEFGHIJKLMNOPQRSTUVWX test@launcher-ux
  service:
    type: ClusterIP
