apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: default
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: e2e23

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e23
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/clusterName
        value: e2e23

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e23-workers
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/controllerRef/name
        value: e2e23
      - op: replace
        path: /spec/controllerRef/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e23
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/controllerRef/name
        value: e2e23
      - op: replace
        path: /spec/controllerRef/namespace
        value: default

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /data/slurm.key
        value: uh7lG/1c5iVVA51MbQFewW2lqrQFzQGpPODh6ioDuQqRNN+aybPAH+UswO4nX6L2tORMKaKiU14A7tP4z9l7yQ==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /data/jwt.key
        value: KjsGm1cFrzNdjtWMWh567J5hEzHxfsqikRl+DNSxL8E=
