{{- if and .Values.auth.enabled (not .Values.auth.existingAdminSecret.name) }}
{{- $secretName := printf "%s-auth-admin-secret" (include "mlflow.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $password := randAlphaNum 32 }}
{{- if and $existing (hasKey $existing.data "password") }}
{{- $password = (index $existing.data "password" | b64dec) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "auth.adminUsername must be specified" .Values.auth.adminUsername | b64enc }}
  password: {{ $password | b64enc }}
{{- end }}
