apiVersion: v1
kind: Secret
metadata:
  name: slurm-auth-slurm
  namespace: CLUSTER_NAMESPACE
type: Opaque
data:
  slurm.key: SLURM_AUTH_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: slurm-auth-jwt
  namespace: CLUSTER_NAMESPACE
type: Opaque
data:
  jwt.key: JWT_AUTH_KEY
