apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/tenant-infra

patches:
  - target:
      kind: Namespace
      name: NAMESPACE
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops06

  - target:
      kind: KamajiControlPlane
      name: CLUSTER_NAME-control-plane
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06-control-plane
      - op: replace
        path: /metadata/namespace
        value: gitops06
      - op: replace
        path: /spec/version
        value: "v1.30.0"
      - op: replace
        path: /spec/network/ingress/hostname
        value: gitops06.k8s.launcher.internal

  - target:
      kind: Cluster
      name: CLUSTER_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06
      - op: replace
        path: /metadata/namespace
        value: gitops06
      - op: replace
        path: /spec/controlPlaneRef/name
        value: gitops06-control-plane
      - op: replace
        path: /spec/infrastructureRef/name
        value: gitops06

  - target:
      kind: OpenStackCluster
      name: CLUSTER_NAME
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06
      - op: replace
        path: /metadata/namespace
        value: gitops06
      - op: replace
        path: /spec/identityRef/name
        value: cloud-config
      - op: replace
        path: /spec/identityRef/cloudName
        value: capi-test
      - op: replace
        path: /spec/externalNetwork/id
        value: fea71d83-27da-4636-9a8b-842f93bcaccf

  - target:
      kind: OpenStackMachineTemplate
      name: CLUSTER_NAME-worker-mt
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06-worker-mt
      - op: replace
        path: /metadata/namespace
        value: gitops06
      - op: replace
        path: /spec/template/spec/flavor
        value: a4v2
      - op: replace
        path: /spec/template/spec/image/filter/name
        value: ubuntu-2404-kube-v1.30.0
      - op: replace
        path: /spec/template/spec/sshKeyName
        value: capi-test
      - op: replace
        path: /spec/template/spec/identityRef/name
        value: cloud-config
      - op: replace
        path: /spec/template/spec/identityRef/cloudName
        value: capi-test

  - target:
      kind: KubeadmConfigTemplate
      name: CLUSTER_NAME-worker-config
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06-worker-config
      - op: replace
        path: /metadata/namespace
        value: gitops06

  - target:
      kind: MachineDeployment
      name: CLUSTER_NAME-md-0
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops06-md-0
      - op: replace
        path: /metadata/namespace
        value: gitops06
      - op: replace
        path: /spec/clusterName
        value: gitops06
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/clusterName
        value: gitops06
      - op: replace
        path: /spec/template/spec/version
        value: v1.30.0
      - op: replace
        path: /spec/template/spec/bootstrap/configRef/name
        value: gitops06-worker-config
      - op: replace
        path: /spec/template/spec/infrastructureRef/name
        value: gitops06-worker-mt

  - target:
      kind: ClusterResourceSet
      name: cilium-cni
    patch: |
      - op: replace
        path: /metadata/namespace
        value: gitops06
