apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-gitops07
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops07

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops07
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops07
      - op: replace
        path: /spec/clusterName
        value: gitops07

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops07-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops07
      - op: replace
        path: /spec/controllerRef/name
        value: gitops07
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops07
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops07
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops07
      - op: replace
        path: /spec/controllerRef/name
        value: gitops07
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops07

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops07
      - op: replace
        path: /data/slurm.key
        value: t8Yh2k4q+CKj6TaFbaQ2Z7EpMo1Okp82Je4vJHi8LTd88QCLMV9vv87eGOMfoiQ1FkGE806r+I/8XKGd0kTi5g==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops07
      - op: replace
        path: /data/jwt.key
        value: mBcZl3WkPGV7PEAEzMVouCY17Bryr+3zsbAiAaMWv44=
