apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: default
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: e2e27

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e27
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/clusterName
        value: e2e27

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e27-workers
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/controllerRef/name
        value: e2e27
      - op: replace
        path: /spec/controllerRef/namespace
        value: default
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e27
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /spec/controllerRef/name
        value: e2e27
      - op: replace
        path: /spec/controllerRef/namespace
        value: default

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /data/slurm.key
        value: jXel5T5W3tEfDAw4ell0hgww/iarqYgzWrBmhkLjpbNqc9RhK7h5T8gL0O1HeynJPsbJpwPhMi6psYoFO5Rpcw==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: default
      - op: replace
        path: /data/jwt.key
        value: Ff1HG5BTryIglLUBIlvd3g0WfcHEyRtU5XqYWOOW8hw=
