apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: CLUSTER_NAME-worker-config
  namespace: NAMESPACE
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: "openstack:///{{ ds.meta_data.uuid }}"
          name: "{{ ds.meta_data.local_hostname }}"
