apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: CLUSTER_NAME
  namespace: NAMESPACE
  labels:
    launcher.supergate.io/cluster-name: CLUSTER_NAME
spec:
  dataStoreName: default
  replicas: 1
  kubernetes:
    version: K8S_VERSION
    kubelet:
      cgroupfs: systemd
      preferredAddressTypes:
        - InternalIP
        - ExternalIP
        - Hostname
  controlPlane:
    service:
      serviceType: ClusterIP
    ingress:
      hostname: CLUSTER_NAME.k8s.launcher.internal
      ingressClassName: nginx-kamaji
      additionalMetadata:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          cert-manager.io/cluster-issuer: kamaji-ca
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        port: 8132
  networkProfile:
    certSANs:
      - CLUSTER_NAME.k8s.launcher.internal
    dnsServiceIPs:
      - "10.96.0.10"
    podCidr: 10.244.0.0/16
    port: 6443
    serviceCidr: 10.96.0.0/12
