apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e14
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: e2e14

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e14
      - op: replace
        path: /metadata/namespace
        value: e2e14
      - op: replace
        path: /spec/clusterName
        value: e2e14

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e14-workers
      - op: replace
        path: /metadata/namespace
        value: e2e14
      - op: replace
        path: /spec/controllerRef/name
        value: e2e14
      - op: replace
        path: /spec/controllerRef/namespace
        value: e2e14
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: e2e14
      - op: replace
        path: /metadata/namespace
        value: e2e14
      - op: replace
        path: /spec/controllerRef/name
        value: e2e14
      - op: replace
        path: /spec/controllerRef/namespace
        value: e2e14

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: e2e14
      - op: replace
        path: /data/slurm.key
        value: IqNFsl6PV4NPqiZkcV70Wlw38Cq5S5+M5I12f7Osz3ptEDBbJFQY6laqo98VvE4S5yQjcOVkIyuaiUabeOGKDA==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: e2e14
      - op: replace
        path: /data/jwt.key
        value: a2JvyW39eh43D/OTArMlZydPSGAYvW8yoo/rU61eJCs=
