
apiVersion: slinky.slurm.net/v1beta1
kind: NodeSet
metadata:
  name: emerald-storm-cluster-big
  namespace: slurm-emerald-storm-cluster
spec:
  controllerRef:
    name: emerald-storm-cluster
    namespace: slurm-emerald-storm-cluster
  replicas: 1
  slurmd:
    resources:
      limits:
        cpu: "3"
        memory: 7Gi
  partition:
    enabled: true
    config: "Name=bigmem MaxTime=72:00:00 AllowGroups=ml-team"
