apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-gitops03
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops03

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops03
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops03
      - op: replace
        path: /spec/clusterName
        value: gitops03

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops03-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops03
      - op: replace
        path: /spec/controllerRef/name
        value: gitops03
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops03
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops03
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops03
      - op: replace
        path: /spec/controllerRef/name
        value: gitops03
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops03

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops03
      - op: replace
        path: /data/slurm.key
        value: syq8aZ2GVoQNRUr7l+MNfjRhHpqZZIg30/s0v0GeFGZD+oz10f+gHzM1gGVxy2VMxBvlE2eVGhiuG7gM3nc0uQ==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops03
      - op: replace
        path: /data/jwt.key
        value: 2hTNv/nhXp7wgIWPWZ1FrVWzcnCRi6O5KzUCf02ePcU=
