apiVersion: v1
kind: Secret
metadata:
  name: timefix-verify-sssd-conf
  namespace: slurm-timefix-verify
type: Opaque
data:
  sssd.conf: W3Nzc2RdCmNvbmZpZ19maWxlX3ZlcnNpb24gPSAyCnNlcnZpY2VzID0gbnNzLCBwYW0KZG9tYWlucyA9IEZJTEVTCgpbbnNzXQpmaWx0ZXJfdXNlcnMgPSByb290CmZpbHRlcl9ncm91cHMgPSByb290CgpbcGFtXQoKW2RvbWFpbi9GSUxFU10KaWRfcHJvdmlkZXIgPSBmaWxlcwplbnVtZXJhdGUgPSB0cnVlCg==
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: timefix-verify-login
  namespace: slurm-timefix-verify
spec:
  controllerRef:
    name: timefix-verify
    namespace: slurm-timefix-verify
  replicas: 1
  sssdConfRef:
    name: timefix-verify-sssd-conf
    key: sssd.conf
  rootSshAuthorizedKeys: |-
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtimefixVERIFY2026 verify@time
  service:
    type: ClusterIP
