apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/slurm-cluster

patches:
  - target:
      kind: Namespace
    patch: |
      - op: replace
        path: /metadata/name
        value: slurm-gitops02
      - op: replace
        path: /metadata/labels/launcher.supergate.io~1cluster-name
        value: gitops02

  - target:
      kind: Controller
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops02
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops02
      - op: replace
        path: /spec/clusterName
        value: gitops02

  - target:
      kind: NodeSet
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops02-workers
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops02
      - op: replace
        path: /spec/controllerRef/name
        value: gitops02
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops02
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/slurmd/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/slurmd/resources/limits/memory
        value: 8Gi

  - target:
      kind: RestApi
    patch: |
      - op: replace
        path: /metadata/name
        value: gitops02
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops02
      - op: replace
        path: /spec/controllerRef/name
        value: gitops02
      - op: replace
        path: /spec/controllerRef/namespace
        value: slurm-gitops02

  - target:
      kind: Secret
      name: slurm-auth-slurm
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops02
      - op: replace
        path: /data/slurm.key
        value: lFh7Tjn6qHHoz4hOAZH04wD+vDtTeOD25rO0Ork6G4SZvsLMttRm6gCJJC2qghBR4RbrjGrSEq7EzDbHy2m/pA==

  - target:
      kind: Secret
      name: slurm-auth-jwt
    patch: |
      - op: replace
        path: /metadata/namespace
        value: slurm-gitops02
      - op: replace
        path: /data/jwt.key
        value: vHqHK25UdluqH6qQkEGLz+G2nl3e5H5pPn87Dc3sIZ0=
