
apiVersion: slinky.slurm.net/v1beta1
kind: NodeSet
metadata:
  name: golden-blaze-cluster-interactive
  namespace: slurm-golden-blaze-cluster
spec:
  controllerRef:
    name: golden-blaze-cluster
    namespace: slurm-golden-blaze-cluster
  replicas: 1
  slurmd:
    resources:
      limits:
        cpu: "3"
        memory: 7Gi
  partition:
    enabled: true
    config: "Name=interactive MaxTime=2:00:00"
