apiVersion: v1
kind: Secret
metadata:
  name: golden-blaze-cluster-sssd-conf
  namespace: slurm-golden-blaze-cluster
type: Opaque
data:
  sssd.conf: W3Nzc2RdCmNvbmZpZ19maWxlX3ZlcnNpb24gPSAyCnNlcnZpY2VzID0gbnNzLCBwYW0KZG9tYWlucyA9IEZJTEVTCgpbbnNzXQpmaWx0ZXJfdXNlcnMgPSByb290CmZpbHRlcl9ncm91cHMgPSByb290CgpbcGFtXQoKW2RvbWFpbi9GSUxFU10KaWRfcHJvdmlkZXIgPSBmaWxlcwplbnVtZXJhdGUgPSB0cnVlCg==
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: golden-blaze-cluster-login
  namespace: slurm-golden-blaze-cluster
spec:
  controllerRef:
    name: golden-blaze-cluster
    namespace: slurm-golden-blaze-cluster
  replicas: 1
  sssdConfRef:
    name: golden-blaze-cluster-sssd-conf
    key: sssd.conf
  service:
    type: ClusterIP
