apiVersion: v1
kind: Secret
metadata:
  name: demo-cluster-sssd-conf
  namespace: slurm-demo-cluster
type: Opaque
data:
  sssd.conf: W3Nzc2RdCmNvbmZpZ19maWxlX3ZlcnNpb24gPSAyCnNlcnZpY2VzID0gbnNzLCBwYW0KZG9tYWlucyA9IEZJTEVTCgpbbnNzXQpmaWx0ZXJfdXNlcnMgPSByb290CmZpbHRlcl9ncm91cHMgPSByb290CgpbcGFtXQoKW2RvbWFpbi9GSUxFU10KaWRfcHJvdmlkZXIgPSBmaWxlcwplbnVtZXJhdGUgPSB0cnVlCg==
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: demo-cluster-login
  namespace: slurm-demo-cluster
spec:
  controllerRef:
    name: demo-cluster
    namespace: slurm-demo-cluster
  replicas: 1
  sssdConfRef:
    name: demo-cluster-sssd-conf
    key: sssd.conf
  rootSshAuthorizedKeys: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOZ310WL9qU+9po8a1OHQZMmLRFYZtBU0ki9WXFAxpEuacRCMiuv6iYLm9tiuAAt7zcautwYbqD1szsiXHLIso1bHMHsn/TlYwrSbOqiV4RcawzPmm0citMcKV1Ge5zAC3O7EN3po6+K0ScrbHeXjVkq6ECPL6x5xAfh+K6X2RafI8mA3rp7cqKveoryJuf9hKHmk3UiInuMABEYKx1XgSgocg+JxXb4Y9mkwRQ2O9+1cNVaKV9VgYkoYLKZ1K9oF/X68cI2kDGVWkFzrJbMVLvl4uCFrsDf3LpwV6ksmz6M6yodr/xn5n6sFgnkSXDd5/J0DFee66UIUAj3vFvBokolEvZRZWEWmDuGX6x4RLI83PNNPMJ+Y7VHWF2aVGAejtd3zP7rN4Oj1dIXDxamz5qLlV8dfLrYZeXM/YnGzeNy6HqwSDC+7aS9Otn+JUu0aU7xBEKWqyYmPacClUSC4fIp9I8IfVMuGOMtj2Wt4KmHJloy94mQCL4/u2RD7vm2s= byeonjaehan@byeonjaehan-ui-MacBookPro.local
  service:
    type: ClusterIP
