apiVersion: v1
kind: Secret
metadata:
  name: amber-forge-cluster-sssd-conf
  namespace: slurm-amber-forge-cluster
type: Opaque
data:
  sssd.conf: W3Nzc2RdCmNvbmZpZ19maWxlX3ZlcnNpb24gPSAyCnNlcnZpY2VzID0gbnNzLCBwYW0KZG9tYWlucyA9IEZJTEVTCgpbbnNzXQpmaWx0ZXJfdXNlcnMgPSByb290CmZpbHRlcl9ncm91cHMgPSByb290CgpbcGFtXQoKW2RvbWFpbi9GSUxFU10KaWRfcHJvdmlkZXIgPSBmaWxlcwplbnVtZXJhdGUgPSB0cnVlCg==
---
apiVersion: slinky.slurm.net/v1beta1
kind: LoginSet
metadata:
  name: amber-forge-cluster-login
  namespace: slurm-amber-forge-cluster
spec:
  controllerRef:
    name: amber-forge-cluster
    namespace: slurm-amber-forge-cluster
  replicas: 1
  sssdConfRef:
    name: amber-forge-cluster-sssd-conf
    key: sssd.conf
  rootSshAuthorizedKeys: |-
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDEMOKEY1234567890abcdef e2e-test@launcher
  service:
    type: ClusterIP
